services:

  postgres:
    container_name: app-postgres
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser#pwd
      POSTGRES_DB: appdb
    volumes:
      - "./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf" 
      - "./postgres/data:/var/lib/postgresql/data:delegated"
      - "./postgres/init:/docker-entrypoint-initdb.d"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"

  web_app:
    container_name: web-app
    image: simple-py-web-app:latest
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
      DB_USER: appuser
      DB_PASSWORD: appuser#pwd
      DB_NAME: appdb
      DB_HOST: app-postgres

networks:
  default:
    name: net
