services:

  web_app:
    container_name: web-app
    image: simple-py-web-app:latest
    #depends_on:
    #  - postgres
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 1
      DB_USER: appuser
      DB_PASSWORD: appuser#pwd
      DB_NAME: appdb
      DB_HOST: app-postgres

networks:
  default:
    name: net
