name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd app && docker build --rm . --file Dockerfile --tag simple-py-web-app:$(date +%s) --tag simple-py-web-app:latest
